name: speech_to_text_example
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # recording words
  speech_to_text: ^6.3.0

  # floating action button effect
  avatar_glow: ^2.0.2

  # launch apps, browser & email
  url_launcher: ^6.2.6

  # copy text to clipboard
  clipboard: ^0.1.3
